### ISSUE TITLE
Improve separation worker/coordinator

### ISSUE THREAD

**Issue by ccamel** [runabol/piper#19]
As far as I understand, the commit 73c8345bb8e40e133735d1ca352bd972abd63b0b has simplified project code structure and put all in one place, in a single jar.

We have a strategy of implementation of the workers in which we need to separate the workers from the coordinator (µService architecture - wrt separation of concerns) and we do not want to embed the code of the coordinator (server) for each of them.

In addition, we plan to implement some workers in go (now that piper supports Kafka). That's why it might be interesting to have some sort of SDK in java, aside of the the piper server project, for the implementation of the workers, who would contain the minimum of code required for that, and a declination for other languages: go, python...

What do you think ?

**Comment by runabol** [comment]
Interesting. That's actually exactly what I do in a version of the product I wrote for a client.

I have a `core` module and a separate `worker` and `coordinator` modules which depend on it. 

I thought it was an overkill for the open source version so I chose not to do it. 

Now, the existing codebase could still act as an SDK since all Coordinator features are inactive/dormant unless explicitly turned on by configuration. e.g. the `Coordinator` bean is completely ignored if `piper.coordinator.enabled=false` which is the default. Same goes for all the web endpoints.

**Comment by ccamel** [comment]
Ok. I see your point. It seems we have similar usages of the project.

Well, actually I don't think it's overkill to have a clean separation of the things - it's a good practice - but it depends on how you consider the project. As far as i understand, this project is a subset of a closed source version ?

**Comment by runabol** [comment]
So the history of this project is that I wrote a close source version of it back in 2015. 

Since I didn't own the IP but liked the project I decided to take the ideas and built it again from scratch and open source it. 

Of course since I had the opportunity to take a completely fresh look I was able to remove some of the rough edges I didn't like with the original version. 

My goal with the open source version is to give the same capabilities in terms of workflow managent while lowering the barrier to entry as much as possible to make it easy for people to adopt it. 

That's the main reason behind deciding to fold the code base into a single jar. It's simpler for a newcomer to try things out with this setup. 

I do think you have a valid point and perhaps worth revisiting in the future based on the feedback we get from the community.

**Comment by ccamel** [comment]
Many thanks for your explanation. I understand the context better.

So, another question: while keeping the project as simple as possible (this is one of the great qualities of the project, to my mind, compared to others), would you still be open to new features? Indeed, in the current state, `piper` does not fit all our needs and some features are missing but `piper` is for now the closest to what we need. :smile:

**Comment by runabol** [comment]
Yes, new features are definitely welcome on a case-by-case basis. Feel free to create new issues for any such ideas and start a conversation.
